# Starts PostgreSQL database and front-end app for development, assuming the back-end service will be built and run separately by developer
version: "3"
services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "50000:50000"
