version: "3"
services:
  game:
    build: game
    ports:
      - "6000:5000"
    volumes:
      - ./game:/app
    depends_on:
      - chessdb
    environment:
      - POSTGRESQL_HOST=chessdb
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=chessdb
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=developer1.

  app:
    build: portal
    environment:
      - POSTGRESQL_HOST=chessdb
      - POSTGRESQL_PORT=5432
      - POSTGRESQL_DATABASE=chessdb
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_PASSWORD=developer1.
    ports:
      - "3000:3000"
      - "50000:50000"

  viewer:
    environment:
      CHOKIDAR_USEPOLLING: "true"
    build:
      context: ./viewer
      dockerfile: ./Dockerfile
    volumes:
      - ./viewer/src:/app/src
    ports:
      - "4000:3000"

  chessdb:
    image: "bitnami/postgresql:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_DATABASE=chessdb
      - POSTGRESQL_PASSWORD=developer1.

  chesstest:
    image: "bitnami/postgresql:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_DATABASE=chesstest
      - POSTGRESQL_PASSWORD=developer1.
